<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE roms [

<!ELEMENT roms ( rom+ ) >
<!ENTITY deg    "&#176;" ><!-- degree sign -->
<!ENTITY micro  "&#181;" ><!-- micro sign -->

<!ELEMENT rom ( romid, table+ ) >
<!ATTLIST rom base CDATA #IMPLIED>

<!ELEMENT romid ( xmlid, internalidaddress, internalidstring, caseid?, ecuid, year, market, make, model, submodel, transmission, flashmethod?, memmodel, filesize, obsolete? ) >

<!ELEMENT xmlid (#PCDATA) >
<!ELEMENT internalidaddress (#PCDATA) >
<!ELEMENT internalidstring (#PCDATA) >
<!ELEMENT caseid (#PCDATA) >
<!ELEMENT ecuid (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT market (#PCDATA) >
<!ELEMENT make (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT submodel (#PCDATA) >
<!ELEMENT transmission (#PCDATA) >
<!ELEMENT flashmethod (#PCDATA) >
<!ELEMENT memmodel (#PCDATA) >
<!ELEMENT filesize (#PCDATA) >
<!ELEMENT obsolete (#PCDATA) >

<!ELEMENT table ( #PCDATA | scaling | table | description | data | state )* >
<!ATTLIST table
	type NMTOKENS #IMPLIED
	name CDATA #IMPLIED
	category CDATA #IMPLIED
	storagetype CDATA #IMPLIED
	endian (little | big) #IMPLIED
	sizex CDATA #IMPLIED
	sizey CDATA #IMPLIED
	userlevel (1 | 2 | 3 | 4 | 5) #IMPLIED
	logparam CDATA #IMPLIED
	storageaddress CDATA #IMPLIED >

<!ELEMENT scaling EMPTY >
<!ATTLIST scaling
	units CDATA #REQUIRED
	expression CDATA #REQUIRED
	to_byte CDATA #REQUIRED
	format CDATA #REQUIRED
	fineincrement CDATA #REQUIRED
	coarseincrement CDATA #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT data (#PCDATA) >

<!ELEMENT state (#PCDATA) >
<!ATTLIST state
	name CDATA #REQUIRED
	data CDATA #REQUIRED >
]>
<roms>
  <rom>
    <!--
v0.0.1
	- draft of MSS50

	In this BASE section define all the common table data and axis attributes.
    Leave out the ROM specific addresses.
-->
  <romid>
   <xmlid>BMWMSS52BASE</xmlid>
   <internalidaddress>0000</internalidaddress>
   <internalidstring>0000</internalidstring>
   <ecuid>0000</ecuid>
   <year>1996-1999</year>
   <market>EU</market>
   <make>BMW</make>
   <model>E36 M3</model>
   <submodel>MSS50</submodel>
   <transmission>MT/AT</transmission>
  </romid>
  
<table type="Switch" name="EWS Delete" category="Config Switches" sizey="1" userlevel="5">
	<state name="EWS - Enable" data="00" />
	<state name="EWS - Delete" data="01" />
	<description>Use this Switch to delete EWS
You will need to supress DTCs 66,130,148 </description>
</table>


<!-- <table type="2D" name="(STFT) Minimum Integrator" category="STFT" storagetype="int16" endian="little"  userlevel="1" sizey="1">
	<scaling units="%" expression="(x*0.003052)-100" to_byte="(x+100)/0.003052" format="0.0" fineincrement=".1" coarseincrement="1" />
	<table type="Static Y Axis" name="Minimum STFT" sizey="1">
		<data>Short Term Fuel Trim (OBD2) - Minimum Limit</data>
	</table>
	<description>(K_LA_FMIN) This table determines the % of additional fuel that can be removed from to the base fueling to achieve stoich (14.7:1) based on O2 feedback</description>
</table> 

<table type="2D" name="(STFT) Maximum Integrator" category="STFT" storagetype="uint16" endian="little"  userlevel="1" sizey="1">
	<scaling units="%" expression="(x*0.003052)-100" to_byte="(x+100)/0.003052" format="0.0" fineincrement=".1" coarseincrement="1" />
	<table type="Static Y Axis" name="Maximum STFT" sizey="1">
		<data>Short Term Fuel Trim (OBD2) - Maximum Limit</data>
	</table>
	<description>(K_LA_FMAX) This table determines the % of additional fuel that can be added to the base fueling to achieve stoich (14.7:1) based on O2 feedback</description>
</table>

<table type="2D" name="(LTFT) Minimum Integrator" category="LTFT" storagetype="int16" endian="little"  userlevel="1" sizey="1">
	<scaling units="%" expression="(x*0.003052)-100" to_byte="(x+100)/0.003052" format="0.0" fineincrement=".1" coarseincrement="1" />
	<table type="Static Y Axis" name="Minimum LTFT" sizey="1">
		<data>Long Term Fuel Trim (OBD2) - Minimum Limit</data>
	</table>
	<description>(K_LAA_FMIN) This table determines the % of additional fuel that can be removed from to the base fueling</description>
</table> 

<table type="2D" name="(LTFT) Maximum Integrator" category="LTFT" storagetype="uint16" endian="little"  userlevel="1" sizey="1">
	<scaling units="%" expression="(x*0.003052)-100" to_byte="(x+100)/0.003052" format="0.0" fineincrement=".1" coarseincrement="1" />
	<table type="Static Y Axis" name="Maximum LTFT" sizey="1">
		<data>Long Term Fuel Trim (OBD2) - Maximum Limit</data>
	</table>
	<description>(K_LAA_FMAX) This table determines the learned % of additional fuel that can be added to the base fueling</description>
</table>

<table type="2D" name="(LTFT) Minimum ECT" category="LTFT" storagetype="uint8" endian="little"  userlevel="1" sizey="1">
   <scaling units="deg" expression="x-48" to_byte="x+48" format="0" fineincrement=".1" coarseincrement="1" />
      <table type="Static Y Axis" name="ECT" sizey="1">
    <data>Coolant Temp</data>
   </table>
<description> (K_LAA_TMOT_MIN) LTFT fueling in disabled below this temperature</description>
</table> 

<table type="2D" name="(LTFT) Maximum ECT" category="LTFT" storagetype="uint8" endian="little"  userlevel="1" sizey="1">
   <scaling units="deg" expression="x-48" to_byte="x+48" format="0" fineincrement=".1" coarseincrement="1" />
      <table type="Static Y Axis" name="ECT" sizey="1">
    <data>Coolant Temp</data>
   </table>
<description> (K_LAA_TMOT_MAX) LTFT fueling is disabled above this temperature</description>
</table> 

<table type="2D" name="(Idle LTFT) Minimum Additive" category="LTFT" storagetype="int16" endian="little"  userlevel="1" sizey="1">
   <scaling units="milliseconds" expression="x*0.001" to_byte="x.0.001" format="0.000" fineincrement=".1" coarseincrement="1" />
      <table type="Static Y Axis" name="Minimum IPW" sizey="1">
    <data>Idle fuel additive</data>
   </table>
<description> (K_LAA_OFFSET_MIN) Additional 'Additive' that is only used near 'idle': Effect = Learned milliseconds removed from current injector pulsewidth</description>
</table> 

<table type="2D" name="(Idle LTFT) Maximum Additive" category="LTFT" storagetype="uint16" endian="little"  userlevel="1" sizey="1">
   <scaling units="milliseconds" expression="x*0.001" to_byte="x/0.001" format="0.000" fineincrement=".1" coarseincrement="1" />
         <table type="Static Y Axis" name="Maximum IPW" sizey="1">
    <data>Idle fuel additive</data>
   </table>
<description> (K_LAA_OFFSET_MAX) Additional 'Additive' that is only used near 'idle': Effect = Learned milliseconds added to current injector pulsewidth</description>
</table> -->

<!--Fuel-->
	<table type="2D" name="Fuel Injection - Dead Time" category="Fuel" storagetype="uint16" endian="big" sizey="5" userlevel="1" >
		<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.000" fineincrement=".01" coarseincrement="0.1" />
			<table type="X Axis" name="Volts" storagetype="uint16" endian="big" >
				<scaling units="V" expression="x*0.1" to_byte="x/0.1" format="0.0" fineincrement="0.01" coarseincrement="0.1" />
			</table>
		<description>(KF_TI_UB) This map is the Fuel injector dead time, which is added to the calculated IPW</description>
	</table>
	
	<table type="3D" name="Fuel Injection - Idle" category="Fuel" storagetype="uint8" endian="little" sizex="8" sizey="3" userlevel="1" >
		<scaling units="Multiplier" expression="x*0.007813" to_byte="x/0.007813" format="0.00" fineincrement=".01" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big" logparam="E2" >
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This map acts as a scalar to the idle fuel map. Values in this table are multiplied to the calculated Injector Pulse Width.
	  Increase these values to lower your STFT closer to 0, lower these values to increase STFT closer to 0.</description>
	</table>

	<table type="3D" name="Fuel Injection - Part Throttle" category="Fuel" storagetype="uint8" endian="little" sizex="18" sizey="12" userlevel="1" >
		<scaling units="Multiplier" expression="x*0.007813" to_byte="x/0.007813" format="0.00" fineincrement=".01" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big" logparam="E2" >
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>(KF_TI_N_RF) This map acts as a scalar to the stock fuel map. Values in this table are multiplied to the calculated Injector Pulse Width.
	  Increase these values to lower your STFT closer to 0, lower these values to increase STFT closer to 0.</description>
	</table>

	<table type="2D" name="Fuel Injection - WOT Enrichment" category="Fuel" storagetype="uint8" endian="little" sizey="18" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.00" fineincrement="0.01" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint8" endian="big">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>(KF_TI_N_RF_VL) Enrichment for fuel under full throttle conditions</description>
	</table>


<!-- 	<table type="2D" name="Fuel Injection - Minimum IPW" category="Fuel" storagetype="uint16" endian="little" sizey="1" userlevel="1">
		<scaling units="ms" expression="x*.001" to_byte="x/.001"  format="0.000" fineincrement="0.001" coarseincrement="1" />
			<table type="Static Y Axis" name="Minimum IPW" sizey="1">
				<data>Minimum Injector Pulse Width</data>
			</table>
		<description>(K_TI_MIN) Use this table to lower the Minimum IPW limit in the DME. Needed for larger injectors</description>
	</table>  

	<table type="2D" name="Fuel Injection - Maximum IPW" category="Fuel" storagetype="uint16" endian="little" sizey="1" userlevel="1">
		<scaling units="ms" expression="x*.001" to_byte="x/.001"  format="0.000" fineincrement="0.001" coarseincrement="1" />
			<table type="Static Y Axis" name="Minimum IPW" sizey="1">
				<data>Maximum Injector Pulse Width</data>
			</table>
		<description>(K_TI_MAX) Use this table to adjust the Maximum IPW limit in the DME. Needed for larger injectors</description>
	</table>
	 -->
<!--Timing-->

	<table type="3D" name="Ignition Timing - Idle" category="Timing" storagetype="int16" endian="big"  userlevel="1" sizex="6" sizey="2">
		<scaling units="deg" expression="x*0.1" to_byte="x/0.1" format="0.0" fineincrement="0.5" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="50" coarseincrement="100" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big" logparam="P8" >
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This ignition timing advance map is used during engine idle mode.</description>
	</table>
	
	<table type="3D" name="Ignition Timing - Part Throttle" category="Timing" storagetype="int16" endian="big" sizex="18" sizey="12" userlevel="1" >
		<scaling units="deg" expression="x*0.1" to_byte="x/0.1" format="0.00" fineincrement=".01" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_TZ_GRUND) This is the main ignition timing advance map</description>
	</table>

	<table type="3D" name="Ignition Timing - Part Throttle - Knock Limited" category="Timing" storagetype="int16" endian="big" sizex="18" sizey="12" userlevel="1" >
		<scaling units="deg" expression="x*0.1" to_byte="x/0.1" format="0.00" fineincrement=".01" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>This is the ignition timing map when experiencing knock</description>
	</table>	
	
	<table type="3D" name="Ignition Timing - WOT" category="Timing" storagetype="int16" endian="big"  userlevel="1" sizex="18" sizey="3">
		<scaling units="deg" expression="x*0.1" to_byte="x/0.1" format="0.0" fineincrement="0.5" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="50" coarseincrement="100" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big" logparam="P8" >
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This ignition timing advance map is used during WOT.</description>
	</table>


<!--Vanos-->

	<table type="3D" name="Intake VANOS - Cold" category="VANOS" storagetype="uint8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="%" expression="x" to_byte="x" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Relative Filling %" storagetype="uint16" endian="big">
				<scaling units="%" expression="x*0.392" to_byte="x/0.392" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_EVAN1_SOLL) Intake VANOS position when engine not at temp</description>
	</table>
	
	<table type="3D" name="Intake VANOS - Warm" category="VANOS" storagetype="uint8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="%" expression="x" to_byte="x" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Relative Filling %" storagetype="uint16" endian="big">
				<scaling units="%" expression="x*0.392" to_byte="x/0.392" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_EVAN1_SOLL) Intake VANOS position at operating temp</description>
	</table>
	
	<table type="3D" name="Exhaust VANOS - Cold" category="VANOS" storagetype="int8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="%" expression="x" to_byte="x" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Relative Filling %" storagetype="uint16" endian="big">
				<scaling units="%" expression="x*0.392" to_byte="x/0.392" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_AVAN1_SOLL) Exhaust VANOS position when engine not at temp</description>
	</table>
 
 	<table type="3D" name="Exhaust VANOS - Warm" category="VANOS" storagetype="int8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="%" expression="x" to_byte="x" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Relative Filling %" storagetype="uint16" endian="big">
				<scaling units="%" expression="x*0.392" to_byte="x/0.392" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_AVAN1_SOLL) Exhaust VANOS position at operating temp</description>
	</table>
 
 
<!--Limiters-->
	<table type="2D" name="Engine Rev Limit" category="Limiters" storagetype="uint16" endian="big" sizey="1" userlevel="1" >
		<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="RPM" sizey="1">
				<data>RPM Limit</data>
			</table>
		<description>(K_N_MAX) The limits the engine RPM </description>
	</table>

	<table type="2D" name="Engine Rev Limit - Dyno mode (VSS error)" category="Limiters" storagetype="uint16" endian="big" sizey="1" userlevel="1" >
		<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="RPM" sizey="1">
				<data>RPM Limit</data>
			</table>
		<description>(K_N_MAX_VFEHLER) The limits the engine RPM in case of VSS signal missing, or when front wheels aren't moving i.e. dyno mode</description>
	</table>

	<table type="2D" name="Vehicle Speed Limit 1" category="Limiters" storagetype="uint16" endian="big" sizey="1" userlevel="1" >
		<scaling units="km/h" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="km/h" sizey="1">
				<data>Speed Limit</data>
			</table>
		<description>Speed Limiter 1</description>
	</table>
	
	<table type="2D" name="Vehicle Speed Limit 2" category="Limiters" storagetype="uint16" endian="big" sizey="1" userlevel="1" >
		<scaling units="km/h" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="km/h" sizey="1">
				<data>Speed Limit</data>
			</table>
		<description>Speed Limiter 1</description>
	</table>
	
	<table type="2D" name="Vehicle Speed Correction (ECU)" category="Limiters" storagetype="uint16" endian="big"  userlevel="1" sizey="1" >
		<scaling units="raw" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name=" " sizey="1">
				<data>Vehicle Speed Correction Factor</data>
			</table>
		<description>Adjust if the Vehicle Speed read by the ECU is not accurate. Decrease this value if the Vehicle Speed is being underestimated.</description>
	</table>

<!--Scalars-->
 
	<table type="2D" name="ECT Sensor Scalar" category="Sensors Scaling" storagetype="uint16" endian="little" sizex="11" userlevel="1">
		<scaling units="°C" expression="(x*0.00390625)-48" to_byte="(x+48)/0.00390625" format="0.00" fineincrement="2" coarseincrement="10"/>
			<table type="Y Axis" name="Voltage" storagetype="uint16" endian="big">
				<scaling units="Volts" expression="x*0.00488" to_byte="x/0.00488" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			</table>
		<description>This is the scaling for the Engine Coolant Temperature sensor.</description>
    </table> 
 
	<table type="2D" name="MAF Scalar" category="Sensors Scaling" storagetype="int16" endian="big" sizey="28" userlevel="1" >
		<scaling units="kg/hr" expression="x*0.25" to_byte="x/0.25" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="Volts" storagetype="uint16" endian="big" >
				<scaling units="Volts" expression="x" to_byte="x" format="0.00" fineincrement="0.1" coarseincrement="1" />
			</table>
		<description>This is the scaling for the MAF sensor</description>
	</table>
 
 
<!--Alpha-N-->

	<table type="3D" name="Calculated Load" category="Alpha-N" storagetype="uint16" endian="big" sizex="7" sizey="6" userlevel="1" >
		<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coarseincrement="10" />
			<table type="X Axis" name="TPS" storagetype="uint16" endian="big">
				<scaling units="%" expression="x*(100/256)" to_byte="x/(100/256)" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="10" coarseincrement="50" />
			</table>
		<description>(KF_RF_N_AQ_REL) This table calculates load based on RPM and TPS position</description>
	</table> 


<!--knock-->
	<table type="3D" name="Knock Detection Threshold - Cylinder 1" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_1) The amount of noise the DME will accept before determining knock</description>
	</table>
	
	<table type="3D" name="Knock Detection Threshold - Cylinder 2" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_2) The amount of noise the DME will accept before determining knock</description>
	</table>
	
	<table type="3D" name="Knock Detection Threshold - Cylinder 3" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_3) The amount of noise the DME will accept before determining knock</description>
	</table>
	
	<table type="3D" name="Knock Detection Threshold - Cylinder 4" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_4) The amount of noise the DME will accept before determining knock</description>
	</table>
	
	<table type="3D" name="Knock Detection Threshold - Cylinder 5" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_5) The amount of noise the DME will accept before determining knock</description>
	</table>
	
	<table type="3D" name="Knock Detection Threshold - Cylinder 6" category="Knock" storagetype="uint16" endian="big" sizex="16" sizey="3" userlevel="1" >
		<scaling units="%" expression="x*(1/1024)" to_byte="x/(1/1024)" format="0.00" fineincrement="0.1" coarseincrement="1" />
			<table type="X Axis" name="RPM" storagetype="uint16" endian="big">
				<scaling units="RPM" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Load" storagetype="uint16" endian="big">
				<scaling units="ms" expression="x*0.001" to_byte="x/0.001" format="0.00" fineincrement="1" coaeincrement="10" />
			</table>
		<description>(KF_KD_KFACT_6) The amount of noise the DME will accept before determining knock</description>
	</table>
	
 

 
<table type="3D" name="DTC - Set 1" category="DTCs" storagetype="uint8" endian="little"  userlevel="1" sizey="127" sizex="14" >
   <scaling units="Decimal" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="5" />
   <table type="Static X Axis" name="Byte" sizex="14">
		<data>DTC Number</data>   
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data></data>
		<data>Modifier</data>
		<data></data>
	</table>
	<table type="Static Y Axis" name="DTC" sizey="127">
		<data>(53) Interface, electric fan (E46)/relay, electric fan, stage 2 (E36/7)</data>
		<data>(130) EWS 3.3 tampering protection</data>
		<data>(16) Signal, crankshaft sensor</data>
		<data>(156) Storing adaptation values not possible</data>
		<data>(157) DME memory fault</data>
		<data>(43) Signal, temperature sensor, radiator outlet</data>
		<data>(30) Internal DME fault</data>
		<data>(1) Driver/relay, fuel pump</data>
		<data>(122) DME internal processor check</data>
		<data>(54) System voltage, main relay</data>
		<data>(126) Crash deactivation, fuel pump</data>
		<data>(13) Signal, oxygen sensor before cat., cyl. 1-3</data>
		<data>(12) Signal, oxygen sensor before cat., cyl. 4-6</data>
		<data>(36) Tank venting valve</data>
		<data>(65) Signal, throttle potentiometer and el. throttle actuator</data>
		<data>(144) Function, oxygen sensor control, cyl. 1-3</data>
		<data>(145) Function, oxygen sensor control, cyl. 4-6</data>
		<data>(123) No CAN-bus signal from SMG</data>
		<data>(7) Signal, camshaft sensor, inlet</data>
		<data>(10) Signal, camshaft sensor, exhaust</data>
		<data>(67) Inlet VANOS, advance valve</data>
		<data>(72) Inlet VANOS, retard valve</data>
		<data>(22) Exhaust VANOS, advance valve</data>
		<data>(21) Exhaust VANOS, retard valve</data>
		<data>(124) Activation, active engine mount</data>
		<data>(125) Function lamp, oil level</data>
		<data>(110) Function light, switch, driving dynamics</data>
		<data>(127) Activation, DMTL pump</data>
		<data>(46) Output, consumption signal KVA</data>
		<data>(47) Output, engine-speed signal TD</data>
		<data>(6) Timeout SMG-CAN</data>
		<data>(66) EWS interface: no communication</data>
		<data>(3) Fuel injector, cyl. 1</data>
		<data>(5) Fuel injector, cyl. 2</data>
		<data>(4) Fuel injector, cyl. 3</data>
		<data>(33) Fuel injector, cyl. 4</data>
		<data>(31) Fuel injector, cyl. 5</data>
		<data>(32) Fuel injector, cyl. 6</data>
		<data>(34) Fuel injector, cyl. 7</data>
		<data>(35) Fuel injector, cyl. 8</data>
		<data>(80) Switch chain, frictional connection</data>
		<data>(158) Reset DME possibly due to overspeed</data>
		<data>(27) DMTL changeover valve</data>
		<data>(174) Multiplicative mixture adaptation, cyl. 1-3 control limit reached</data>
		<data>(175) Multiplicative mixture adaptation, cyl. 4-6 control limit reached</data>
		<data>(176) Abort, Tank leakage diagnosis, due to moisture</data>
		<data>(177) MIL lights up due to prompt from SMG</data>
		<data>(178) Catalytic converter conversion, cyl. 1-3</data>
		<data>(179) Catalytic converter conversion, cyl. 4-6</data>
		<data>(180) Tank leak detected</data>
		<data>(181) Fuel filler cap open/missing</data>
		<data>(28) Function, map cooling</data>
		<data>(18) VANOS pressure-accumulator valve</data>
		<data>(87) Signal, oxygen sensor after cat., cyl. 1-3</data>
		<data>(88) Signal, oxygen sensor after cat., cyl. 4-6</data>
		<data>(37) Oxygen sensor heater before cat., cyl. 1-3</data>
		<data>(38) Oxygen sensor heater before cat., cyl. 4-6</data>
		<data>(39) Oxygen sensor heater after cat., cyl. 1-3</data>
		<data>(40) Oxygen sensor heater after cat., cyl. 4-6</data>
		<data>(151) Internal DME fault</data>
		<data>(90) Trim control, cyl. 1-3</data>
		<data>(91) Trim control, cyl. 4-6</data>
		<data>(92) Oxygen sensor after cat., cyl. 1-3: voltage monitoring</data>
		<data>(93) Oxygen sensor after cat., cyl. 4-6: voltage monitoring</data>
		<data>(182) Internal DME fault</data>
		<data>(183) Internal DME fault</data>
		<data>(100) Internal error</data>
		<data>(101) Signal, tire pressure, front right</data>
		<data>(102) Signal, tire pressure, rear right</data>
		<data>(103) Signal, tire pressure, rear left</data>
		<data>(184) Function, inlet VANOS</data>
		<data>(185) Function, exhaust VANOS</data>
		<data>(25) Ignition coil, cyl. 1</data>